---
- name: setup /etc/hosts on all machines
  hosts: all
  gather_facts: false
  tasks:
    - name: setup /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item.value }} {{ item.key }}"
      loop: "{{ static_hosts | dict2items }}"

