---
- name: setup /etc/hosts on all kubernetes hosts
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: setup etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ item.value }} {{ item.key }}"
    loop: "{{ static_hosts | dict2items }}"

- name: setup /etc/hosts on all loadbalancer hosts
  hosts: loadbalancers
  tasks:
  - name: setup etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ item.value }} {{ item.key }}"
    loop: "{{ static_hosts | dict2items }}"

- name: apply common config to all kubernetes hosts
  hosts: kubernetes
  become: yes
  become_method: sudo
  roles:
    - common
