---
- name: apply common config to all kubernetes hosts
  hosts: kubernetes
  become: yes
  become_method: sudo
  roles:
    - common

- name: apply config to all kubernetes masters
  hosts: masters
  become: yes
  become_method: sudo
  roles:
    - keepalived
