---
- name: reload sysctl
  ansible.builtin.shell: sysctl --system

- name: docker running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: docker

- name: reconfigure containerd
  ansible.builtin.systemd:
    state: restarted
    daemon_reload : yes
    name: containerd

- name: kubelet running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: kubelet

- name: reconfigure kubelet
  ansible.builtin.systemd:
    state: restarted
    daemon_reload : yes
    name: kubelet
