---
- name: download containerd release
  ansible.builtin.get_url:
    checksum: "sha256:https://github.com/containerd/containerd/releases/download/v{{ containerd_version | default('1.6.8') }}/containerd-{{ containerd_version | default('1.6.8') }}-linux-amd64.tar.gz.sha256sum"
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version | default('1.6.8') }}/containerd-{{ containerd_version | default('1.6.8') }}-linux-amd64.tar.gz"
    dest: /tmp/containerd.tar.gz
  register: containerd_download

- name: extract containerd.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/containerd.tar.gz
    dest: /usr/local
    remote_src: yes
  when: containerd_download.changed

- name: download containerd.service
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /usr/lib/systemd/system/containerd.service

- name: create containerd config dir
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: copy config.toml
  ansible.builtin.copy:
    src: files/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart containerd

- name: enable service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: containerd

- name: download runc
  ansible.builtin.get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version | default('1.1.1') }}/runc.amd64"
    dest: /usr/local/sbin/runc
    owner: root
    group: root
    mode: 0755

- name: setup cni dir
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory

- name: download cni plugins
  ansible.builtin.get_url:
    checksum: "sha256:https://github.com/containernetworking/plugins/releases/download/v{{ cniplugins_version | default('1.1.1') }}/cni-plugins-linux-amd64-v{{ cniplugins_version | default('1.1.1') }}.tgz.sha256"
    url: "https://github.com/containernetworking/plugins/releases/download/v{{ cniplugins_version | default('1.1.1') }}/cni-plugins-linux-amd64-v{{ cniplugins_version | default('1.1.1') }}.tgz"
    dest: /tmp/cni.tar.gz
  register: cniplugins_download

- name: extract cni.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/cni.tar.gz
    dest: /opt/cni/bin/
    remote_src: yes
  notify: reconfigure containerd
  when: cniplugins_download.changed

- name: download nerdctl
  ansible.builtin.get_url:
    checksum: "sha256:https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version | default('0.19.0') }}/SHA256SUMS"
    url: "https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version | default('0.19.0') }}/nerdctl-{{ nerdctl_version | default('0.19.0') }}-linux-amd64.tar.gz"
    dest: /tmp/nerdctl.tar.gz
  register: nerdctl_download

- name: extract nerdctl.tar.gz
  ansible.builtin.unarchive:
    src: /tmp/nerdctl.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  when: nerdctl_download.changed
