---
- name: setup etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"
  loop: "{{ static_hosts | dict2items }}"
  tags:
    - local

- name: enable br_netfilter module
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  notify: reload sysctl

- ansible.builtin.shell: modprobe overlay
- ansible.builtin.shell: modprobe br_netfilter

- name: enable iptables for bridged traffic
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
  notify: reload sysctl

- name: disable swap
  ansible.builtin.shell: swapoff -a
  register: swapoff
  changed_when: swapoff.stdout != ""

- name: remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regex: 'swap'
    state: absent

- import_tasks: containerd.yaml
- import_tasks: kube.yaml
