---
- name: setup etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"
  loop: "{{ static_hosts | dict2items }}"
- name: enable br_netfilter module
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
  notify: reload sysctl
- name: enable iptables for bridged traffic
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  notify: reload sysctl
- name: disable swap
  ansible.builtin.shell: swapoff -a
- name: remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regex: 'swap'
    state: absent
- import_tasks: docker.yml
- import_tasks: kube.yml